### PR TITLE
Update docs about prior participation criteria (fixes #363)

### LINKED ISSUE #363: Update docs on study prior participation criteria
We need to add/clarify a few things in the docs to go along with the changes to the 'must have/not have participated' study eligibility criteria:
- https://github.com/lookit/lookit-api/issues/1302
- https://github.com/lookit/lookit-api/issues/1306

Specifically, the docs should clarify the following:
- How prior study participation is checked: we count any non-empty responses to internal studies as having participated, even if the participant does not finish. We also count any attempt to do external studies (since we have no way of knowing if the child completed an external study). 
- If the researcher wants to prevent a child from doing their study more than once, they can add the study itself to the 'must not have participated' list, keeping in mind that the child will not be considered eligible if they start the study but don't finish. We can point researchers to alternatives if they want to implement the study participation criteria in a different way (e.g. get past sessions from protocol generator to check that they haven't _completed_ the current study).
- If there are multiple studies in the 'must have participated' list for study eligibility, the child must have participated in ALL of studies in the list. That is, in order to be eligible, they must have participated in study1 AND study2 AND ... studyN.
- If there are multiple studies in the 'must not have participated' list for study eligibility, the child is only eligible if they have not participated in ANY of the studies in the list. 
- If the child is not eligible due to the study's prior participation requirements, they can still choose to participate in the study, but they will see a 'red text' warning below the 'Participate Now' button when the ineligible child is selected.

### PR DESCRIPTION
**Pull request by becky-gilbert**
Fixes #363 

docs1

docs2

docs3

docs4

docs5

docs6

### CODE REVIEW

**Review by bleonar5 — APPROVED** [review]

**Comment by mekline** [comment]
Great! Only two possible issues I saw were: 

- There are two callout boxes for "What counts as participated", but I assume you only want the second one?   Could you also add this to the end of the first paragraph: "Since the definition for these criteria has to be used for every study on the site, we have to use a definition of "participated" that operates in the same way for all studies."

- You mention an example in the EFP docs for using the protocol generator but I think there's a link missing. You also might want to explicitly say that you should *not* block the prerequisite study in the criteria, but then include questions at the beginning of the session to determine whether the family is really eligible.

**Comment by mekline** [comment]
Otherwise looks great to me!

**Comment by becky-gilbert** [comment]
Thanks @mekline!

> There are two callout boxes for "What counts as participated", but I assume you only want the second one? 

Ah, there's actually only one. It looks like there's two because of my overlapping screenshots. Here's what it looks like:

Screenshot 2023-11-20 at 3 44 33 PM

> Could you also add this to the end of the first paragraph: "Since the definition for these criteria has to be used for every study on the site, we have to use a definition of "participated" that operates in the same way for all studies."

Yes, done! See screenshot above.

> You mention an example in the EFP docs for using the protocol generator but I think there's a link missing. 

Ah yes, sorry. I think this is because I've added a new section label to the EFP docs and the lookit docs won't be able to find that label until the EFP docs are changed on the master branch. So I _think_ the missing link will appear once everything is merged. After merging I will check and fix it if not!

> You also might want to explicitly say that you should not block the prerequisite study in the criteria, but then [EDIT, SORRY] use previous session logic during the beginning of the session to determine whether the family is really eligible.

Ah yes, makes sense. I tried to clarify this but struggled with the wording. My changes are shown in the screenshot above, 2nd paragraph from the bottom. Let me know if you have suggestions!

**Comment by mekline** [comment]
All looks great, thanks!

**Pull request merged**
